"""Shared data shapes. Import from here, not from the submodules."""

from .abm import (
    EmailCadence,
    EmailStep,
    FollozeBoardSpec,
    FollozeContentModule,
    LinkedInSequence,
    LinkedInStep,
    SalesPlaybook,
)
from .analytics import MetricBundle, MetricTable
from .brand import DraftedResponse, RapidResponsePackage
from .campaign_design import (
    Battlecard,
    CampaignBrief,
    CampaignIdea,
    ObjectionHandler,
)
from .content import (
    AnchorAsset,
    AssetGrid,
    AssetGridItem,
    AssetSection,
    CampaignVariantPackage,
    LocalizedAsset,
)
from .crm import (
    AS_OF,
    OPEN_STAGES,
    Account,
    Campaign,
    CampaignType,
    Contact,
    EngagementEvent,
    EventAttendee,
    FieldEvent,
    IntentSignal,
    OppStage,
    Opportunity,
    Region,
)
from .decks import DeckSpec, Slide, SlideLayout
from .enrichment import CompanyFacts, Technographic
from .knowledge import ICPDefinition, Persona, ProductFeature, RegulatoryGuide
from .market import (
    Competitor,
    NewsItem,
    Review,
    ShareOfVoiceEntry,
    SocialMention,
)
from .marketing_ops import (
    CampaignResult,
    CampaignSpec,
    DeploymentResult,
    ListLoadIssue,
    ListLoadReport,
    SegmentFilter,
    SegmentResult,
)

__all__ = [
    "AS_OF",
    "OPEN_STAGES",
    "Account",
    "AnchorAsset",
    "AssetGrid",
    "AssetGridItem",
    "AssetSection",
    "Battlecard",
    "Campaign",
    "CampaignBrief",
    "CampaignIdea",
    "CampaignResult",
    "CampaignSpec",
    "CampaignType",
    "CampaignVariantPackage",
    "CompanyFacts",
    "Competitor",
    "Contact",
    "DeckSpec",
    "DeploymentResult",
    "DraftedResponse",
    "EmailCadence",
    "EmailStep",
    "EngagementEvent",
    "EventAttendee",
    "FieldEvent",
    "FollozeBoardSpec",
    "FollozeContentModule",
    "ICPDefinition",
    "IntentSignal",
    "LinkedInSequence",
    "LinkedInStep",
    "ListLoadIssue",
    "ListLoadReport",
    "LocalizedAsset",
    "MetricBundle",
    "MetricTable",
    "NewsItem",
    "ObjectionHandler",
    "OppStage",
    "Opportunity",
    "Persona",
    "ProductFeature",
    "RapidResponsePackage",
    "Region",
    "RegulatoryGuide",
    "Review",
    "SalesPlaybook",
    "SegmentFilter",
    "SegmentResult",
    "ShareOfVoiceEntry",
    "Slide",
    "SlideLayout",
    "SocialMention",
    "Technographic",
]
